apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cluster-local-01
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local  
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go
