apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blue-green-01
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/knative-route-demo:green # The URL to the sample app docker image
          env:
            - name: T_VERSION
              value: "green"
  traffic:
  - percent: 100
    revisionName: blue-green-01-x9zmf
  - tag: v2
    latestRevision: true
    percent: 0
