apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blue-green-01
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/knative-route-demo:blue # The URL to the sample app docker image
          env:
            - name: T_VERSION
              value: "blue"
