apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: autoscaling-test-01
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go
      containerConcurrency: 5
